# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deep-watch-rapp.fullname" . }}
  labels:
  {{- include "deep-watch-rapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ template "deep-watch-rapp.fullname" . }}
      app: deep-watch-rapp
      resource: {{ template "deep-watch-rapp.fullname" . }}
  {{- include "deep-watch-rapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        proxy.onosproject.org/inject: "true"
      labels:
        name: {{ template "deep-watch-rapp.fullname" . }}
        app: deep-watch-rapp
        resource: {{ template "deep-watch-rapp.fullname" . }}
    {{- include "deep-watch-rapp.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "secsm/main.py"
            - "--mobiflow-config={{ .Values.config.servicePath }}/mobiflow.json"
            - "--rpc-addr={{ .Values.config.mobiflow.rpc_addr }}"
            - "--rpc-port={{ .Values.config.mobiflow.rpc_port }}"
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /status
              port: 8080
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: mobiflow
              mountPath: {{ .Values.config.mobiflow.sqlite3_db_path }}
            - name: secret
              mountPath: /etc/onos/certs
              readOnly: true
            - name: config
              mountPath: {{ .Values.config.servicePath }}
              readOnly: false
            - name: onos
              mountPath: {{ .Values.config.configPath }}
              readOnly: false
            - name: staticfiles
              mountPath: /tmp
              readOnly: false
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: mobiflow
        - name: secret
          secret:
            secretName: {{ template "deep-watch-rapp.fullname" . }}-secret
        - name: config
          configMap:
            name: {{ template "deep-watch-rapp.fullname" . }}-config
        - name: onos
          configMap:
            name: {{ template "deep-watch-rapp.fullname" . }}-config
        - name: staticfiles
          hostPath:
            path: /tmp
            type: Directory
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}

